program: scripts/train.py
name: width 
method: grid
entity: cbs
project: cbs
group: cbs-width
parameters:
  model.mlp_hidden_size:
    values: [8192]
  model.d_model:
    values: [2048]
  sweep_bs_steps:
    values: ['64-610000', '2048-11719', '4096-10000', '8192-8500', '1024-26000', '128-260000', '256-93750', '512-48000'] 
  sweep_opt_momentum:
    values: [adamw_0.95]
  model.max_sequence_length:
    values: [512]
  optimizer.learning_rate:
    values: [3.16e-3]
  optimizer.ewa_decay:
    values: [0.998]
  scheduler.warmup_ratio:
    values: [0.25]
  chinchilla_token:
    values: [24_000_000]
  scheduler.name:
    values: [constant]
  device_train_microbatch_size:
    values: [64]

command:
  - ${DATA_PATH}/cbs/configs/critical-bs/sweeps/8gpu_macro14.sh
  - ${program}
  - "configs/critical-bs/width.yaml" 
  - "--sweep=true"
  - ${args}