program: scripts/train.py
name: width 
method: grid
entity: cbs
project: cbs
group: cbs-width
parameters:
  model.mlp_hidden_size:
    values: [10240]
  model.d_model:
    values: [2560]
  model.n_heads:
    values: [40]
  sweep_bs_steps:
    values: [ '64-708000', '128-314667', '256-147500', '512-78667', '1024-47200', '2048-29893', '4096-20453', '8192-16520']
  sweep_opt_momentum:
    values: [adamw_0.95]
  model.max_sequence_length:
    values: [512]
  optimizer.learning_rate:
    values: [3.16e-3]
  optimizer.ewa_decay:
    values: [0.998]
  optimizer.beta2:
    values: [0.999]
  scheduler.warmup_ratio:
    values: [0.25]
  chinchilla_token:
    values: [37_760_000] 
  scheduler.name:
    values: [constant]
  device_train_microbatch_size:
    values: [32]

command:
  - ${DATA_PATH}/cbs/configs/critical-bs/sweeps/8gpu_macro16.sh
  - ${program}
  - "configs/critical-bs/width.yaml" 
  - "--sweep=true"
  - ${args}