program: scripts/train.py
name: 151M 
method: grid
entity: cbs
project: cbs
group: cbs-scheduler-151M
parameters:
  sweep_bs_steps:
    values: ['64-196000', '128-80000', '256-52000', '512-12500', '1024-12000', '2048-8000', '4096-7800', '8192-7600']
  sweep_opt_momentum:
    values: [adamw_0.95, adamw_0.99, adamw_0.9, adamw_0.8]
  optimizer.learning_rate:
    values: [3.16e-3]
  optimizer.ewa_decay:
    values: [0.998]
  optimizer.beta2:
    values: [0.95]
  scheduler.warmup_ratio:
    values: [0.25]
  scheduler.name:
    values: [constant]
  chinchilla_token:
    values: [6_000_000]
  model.max_sequence_length:
    values: [512]
  device_train_microbatch_size:
    values: [128]
  seed:
    values: [0]

command:
  - ${DATA_PATH}/cbs/configs/critical-bs/sweeps/8gpu_macro14.sh
  - ${program}
  - "configs/critical-bs/ablation.yaml" 
  - "--sweep=true"
  - ${args}