program: scripts/train.py
name: 302M
method: grid
entity: cbs
project: cbs
group: cbs-302M
parameters:
  sweep_bs_steps: 
    values: ['64-197000', '128-93750', '256-46875', '512-26000', '1024-14000', '2048-8400', '4096-6000', '8192-4500', '16384-4000'] 
  sweep_opt_momentum: 
    values: [adamw_0.95]
  optimizer.beta2:
    values: [0.99]
  optimizer.learning_rate:
    values: [3.16e-3]
  optimizer.ewa_decay:
    values: [0.99]
  scheduler.warmup_ratio:
    values: [0.25]
  scheduler.name:
    values: [constant]
  model.max_sequence_length:
    values: [512]
  device_train_microbatch_size:
    values: [64] 
  seed:
    values: [0]

command:
  - ${DATA_PATH}/cbs/configs/critical-bs/sweeps/8gpu_macro13.sh
  - ${program}
  - "configs/critical-bs/302M.yaml"
  - "--sweep=true"
  - ${args}